apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: micro
spec:
  selector:
    app: web-frontend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
  type: NodePort