apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: micro
spec:
  selector:
    app: web-frontend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP


