apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: micro
spec:
  selector:
    app: web-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  type: NodePort