apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deployer
  namespace: micro
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deployer-role
  namespace: micro
rules:
  - apiGroups: ["", "apps", "autoscaling"]
    resources: ["deployments", "services", "pods", "replicasets", "horizontalpodautoscalers", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer-binding
  namespace: micro
subjects:
  - kind: ServiceAccount
    name: jenkins-deployer
    namespace: micro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-deployer-role


