apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: micro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: ${REGISTRY}/auth-api:${IMAGE_TAG}
          ports:
            - containerPort: 8000
          env:
            - name: AUTH_API_PORT
              value: "8000"
            - name: USERS_API_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: micro-config
                  key: USERS_API_ADDRESS
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: micro-config
                  key: JWT_SECRET
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "400m"
              memory: "256Mi"


