apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor
  namespace: micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-message-processor
  template:
    metadata:
      labels:
        app: log-message-processor
    spec:
      containers:
        - name: log-message-processor
          image: ${REGISTRY}/log-message-processor:${IMAGE_TAG}
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"


