apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
  namespace: micro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
        - name: todos-api
          image: ${REGISTRY}/todos-api:${IMAGE_TAG}
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: USERS_API_URL
              value: "http://users-api.micro.svc.cluster.local:8080"
            - name: ZIPKIN_URL
              value: "http://zipkin.observability.svc.cluster.local:9411"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"


