apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: micro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: ${REGISTRY}/users-api:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "600m"
              memory: "512Mi"


